"OrderedValue.Customize" = "{{.Key}}校验失败"
"OrderedValue.Required" = "{{.Key}}不能为空"
"OrderedValue.Gt" = "{{.Key}}必须大于{{.Value}}"
"OrderedValue.Gte" = "{{.Key}}必须大于等于{{.Value}}"
"OrderedValue.Lt" = "{{.Key}}必须小于{{.Value}}"
"OrderedValue.Lte" = "{{.Key}}必须小于等于{{.Value}}"
"OrderedValue.In" = "{{.Key}}必须包含在{{.Value}}之内"

"SliceValue.Customize" = "{{.Key}}校验失败"
"SliceValue.Required" = "{{.Key}}不能为空"
"SliceValue.Eq" = "{{.Key}}长度必须等于{{.Value}}"
"SliceValue.Gt" = "{{.Key}}长度必须大于{{.Value}}"
"SliceValue.Gte" = "{{.Key}}长度必须大于等于{{.Value}}"
"SliceValue.Lt" = "{{.Key}}长度必须小于{{.Value}}"
"SliceValue.Lte" = "{{.Key}}长度必须小于等于{{.Value}}"
"SliceValue.Contains" = "{{.Key}}必须包含{{.Value}}"

"StringValue.Customize" = "{{.Key}}校验失败"
"StringValue.ParseRegexp" = "正则表达式解析失败"
"StringValue.Required" = "{{.Key}}不能为空"
"StringValue.Eq" = "{{.Key}}长度必须等于{{.Value}}"
"StringValue.Gt" = "{{.Key}}长度必须大于{{.Value}}"
"StringValue.Gte" = "{{.Key}}长度必须大于等于{{.Value}}"
"StringValue.Lt" = "{{.Key}}长度必须小于{{.Value}}"
"StringValue.Lte" = "{{.Key}}长度必须小于等于{{.Value}}"
"StringValue.In" = "{{.Key}}必须包含在{{.Value}}之内"
"StringValue.MatchString" = "{{.Key}}必须和给定的正则表达式相匹配"
"StringValue.MatchRegexp" = "{{.Key}}必须和给定的正则表达式相匹配"
"StringValue.IPv4" = "{{.Key}}格式必须为 ipv4"
"StringValue.IPv6" = "{{.Key}}格式必须为 ipv6"
"StringValue.URL" = "{{.Key}}格式必须为 url"
"StringValue.Base64" = "{{.Key}}格式必须为 base64"
"StringValue.Hex" = "{{.Key}}格式必须为 hex"
"StringValue.Email" = "{{.Key}}格式必须为 email"
"StringValue.Alphabet" = "{{.Key}}必须由字母组成"
"StringValue.Numeric" = "{{.Key}}必须由数字组成"
"StringValue.AlphabetNumeric" = "{{.Key}}必须由字母或数字组成"
"StringValue.Lowercase" = "{{.Key}}必须由小写字母组成"
"StringValue.Uppercase" = "{{.Key}}必须由大写字母组成"

"PointerValue.Required" = "{{.Key}}不能为空"
"PointerValue.Customize" = "{{.Key}}校验失败"

"AnyValue.Customize" = "{{.Key}}校验失败"
