"OrderedValue.Customize" = "Data validation failed"
"OrderedValue.Required" = "{{.Key}} is required"
"OrderedValue.Gt" = "{{.Key}} should great than {{.Value}}"
"OrderedValue.Gte" = "{{.Key}} should great or equal than {{.Value}}"
"OrderedValue.Lt" = "{{.Key}} should less than {{.Value}}"
"OrderedValue.Lte" = "{{.Key}} should less or equal than {{.Value}}"
"OrderedValue.IncludeBy" = "{{.Key}} should be one of {{.Value}}"
"OrderedValue.ExcludeBy" = "{{.Key}} should not be one of {{.Value}}"

"SliceValue.Customize" = "Data validation failed"
"SliceValue.Required" = "{{.Key}} is required"
"SliceValue.Eq" = "Size of {{.Key}} should equal to {{.Value}}"
"SliceValue.Gt" = "Size of {{.Key}} should great than {{.Value}}"
"SliceValue.Gte" = "Size of {{.Key}} should great or equal than {{.Value}}"
"SliceValue.Lt" = "Size of {{.Key}} should less than {{.Value}}"
"SliceValue.Lte" = "Size of {{.Key}} should less or equal than {{.Value}}"
"SliceValue.Include" = "{{.Key}} should contains {{.Value}}"
"SliceValue.Exclude" = "{{.Key}} should not contains {{.Value}}"

"StringValue.Customize" = "Data validation failed"
"StringValue.ParseRegexp" = "Regexp parsing failure"
"StringValue.Required" = "{{.Key}} is required"
"StringValue.Eq" = "Length of {{.Key}} should equal to {{.Value}}"
"StringValue.Gt" = "Length of {{.Key}} should great than {{.Value}}"
"StringValue.Gte" = "Length of {{.Key}} should great or equal than {{.Value}}"
"StringValue.Lt" = "Length of {{.Key}} should less than {{.Value}}"
"StringValue.Lte" = "Length of {{.Key}} should less or equal than {{.Value}}"
"StringValue.IncludeBy" = "{{.Key}} should be one of {{.Value}}"
"StringValue.ExcludeBy" = "{{.Key}} should not be one of {{.Value}}"
"StringValue.MatchString" = "{{.Key}} should match the regexp"
"StringValue.MatchRegexp" = "{{.Key}} should match the regexp"
"StringValue.IPv4" = "format of %{{.Key}} should be ipv4"
"StringValue.IPv6" = "format of %{{.Key}} should be ipv6"
"StringValue.URL" = "format of %{{.Key}} should be url"
"StringValue.Base64" = "format of %{{.Key}} should be base64"
"StringValue.Hex" = "format of %{{.Key}} should be hex"
"StringValue.Email" = "format of %{{.Key}} should be email"
"StringValue.Alphabet" = "format of %{{.Key}} should be alphabet"
"StringValue.Numeric" = "format of %{{.Key}} should be numeric"
"StringValue.AlphabetNumeric" = "format of %{{.Key}} should be alphabet or alphabet"
"StringValue.Lowercase" = "format of %{{.Key}} should be lowercase"
"StringValue.Uppercase" = "format of %{{.Key}} should be uppercase"

"PointerValue.Required" = "{{.Key}} is required"
"PointerValue.Customize" = "Data validation failed"

"AnyValue.Customize" = "Data validation failed"
