["AnyValue.Customize"]
hash = "sha1-9d54cba8b20dbb9962048542cfd9a1e7a6137e4a"
other = "{{.Key}}校验失败"

["OrderedValue.Between"]
hash = "sha1-40e9794969dc4c7e28e2a93758df695f5f78a747"
other = "{{.Key}}必须满足{{.Arg0}}<=x<{{.Arg1}}"

["OrderedValue.Customize"]
hash = "sha1-9d54cba8b20dbb9962048542cfd9a1e7a6137e4a"
other = "{{.Key}}校验失败"

["OrderedValue.Gt"]
hash = "sha1-9e9e2d9e7c7c16267bea53b0b766da11f1aebfba"
other = "{{.Key}}必须大于{{.Arg0}}"

["OrderedValue.Gte"]
hash = "sha1-bbb9001a73aad3c1ba5e7a5fb5e7aaca685b5bf2"
other = "{{.Key}}必须大于等于{{.Arg0}}"

["OrderedValue.In"]
hash = "sha1-f62c039b8c1d6341acd56debdcf19c7724b5c9f9"
other = "{{.Key}}必须包含在{{.Arg0}}之内"

["OrderedValue.Lt"]
hash = "sha1-317b02256bb2dfdef8094c6502a3607791070b40"
other = "{{.Key}}必须小于{{.Arg0}}"

["OrderedValue.Lte"]
hash = "sha1-1f66d0ab733e3cdba351f31996f885dc346bc50d"
other = "{{.Key}}必须小于等于{{.Arg0}}"

["OrderedValue.Required"]
hash = "sha1-62b3289db46dac62320dc8987c9e8d943f4ea05f"
other = "{{.Key}}不能为空"

["PointerValue.Customize"]
hash = "sha1-9d54cba8b20dbb9962048542cfd9a1e7a6137e4a"
other = "{{.Key}}校验失败"

["PointerValue.Required"]
hash = "sha1-62b3289db46dac62320dc8987c9e8d943f4ea05f"
other = "{{.Key}}不能为空"

["SliceValue.Contains"]
hash = "sha1-48927fd9f2922a4c6f699f995d0cc29cd596924d"
other = "{{.Key}}必须包含{{.Arg0}}"

["SliceValue.Customize"]
hash = "sha1-9d54cba8b20dbb9962048542cfd9a1e7a6137e4a"
other = "{{.Key}}校验失败"

["SliceValue.Eq"]
hash = "sha1-55f76c9fa8ea7f113a5deba98f294c03b8ad2551"
other = "{{.Key}}长度必须等于{{.Arg0}}"

["SliceValue.Gt"]
hash = "sha1-90b3594996f9696b6649319f47bc52b5728d9e54"
other = "{{.Key}}长度必须大于{{.Arg0}}"

["SliceValue.Gte"]
hash = "sha1-836f2574dd10698f402b75a2687a54f590397821"
other = "{{.Key}}长度必须大于等于{{.Arg0}}"

["SliceValue.Lt"]
hash = "sha1-eafbb38a0c6b037dc4f8d8f7867b5cb3c0440159"
other = "{{.Key}}长度必须小于{{.Arg0}}"

["SliceValue.Lte"]
hash = "sha1-c94919175fb56b7c7a31149729d6659a0d18b6a1"
other = "{{.Key}}长度必须小于等于{{.Arg0}}"

["SliceValue.Required"]
hash = "sha1-62b3289db46dac62320dc8987c9e8d943f4ea05f"
other = "{{.Key}}不能为空"

["StringValue.Alphabet"]
hash = "sha1-d4e12210fbf6173761e99e07898dca01d175f509"
other = "{{.Key}}必须由字母组成"

["StringValue.AlphabetNumeric"]
hash = "sha1-4f8ac93ec453b5b2f4459f3c7841fe7f859265bf"
other = "{{.Key}}必须由字母或数字组成"

["StringValue.Base64"]
hash = "sha1-c9e7e0e7993963054edf096382b9db754039af20"
other = "{{.Key}}格式必须为 base64"

["StringValue.Between"]
hash = "sha1-40e9794969dc4c7e28e2a93758df695f5f78a747"
other = "{{.Key}}必须满足{{.Arg0}}<=x<{{.Arg1}}"

["StringValue.Customize"]
hash = "sha1-9d54cba8b20dbb9962048542cfd9a1e7a6137e4a"
other = "{{.Key}}校验失败"

["StringValue.Email"]
hash = "sha1-bd4a0aade45dd290eb3c97721a9eda96e56d2aa7"
other = "{{.Key}}格式必须为 email"

["StringValue.Eq"]
hash = "sha1-adc91ec40336e4a50601cde0f6e309825be53a97"
other = "{{.Key}}长度必须等于{{.Arg0}}"

["StringValue.Gt"]
hash = "sha1-5ac360c8fd6dfbedc4e5892724b8fab60df5b8b8"
other = "{{.Key}}长度必须大于{{.Arg0}}"

["StringValue.Gte"]
hash = "sha1-17904b74109b5d86cfef8e99ff89e00e4bf9398d"
other = "{{.Key}}长度必须大于等于{{.Arg0}}"

["StringValue.Hex"]
hash = "sha1-939c389174324cfcd600c7bccf98f93c50b46a1f"
other = "{{.Key}}格式必须为 hex"

["StringValue.IPv4"]
hash = "sha1-4bde492bbbae85aa994bfd8f1c250c253671b67a"
other = "{{.Key}}格式必须为 ipv4"

["StringValue.IPv6"]
hash = "sha1-4922dd749c241a3a7f1849c2bdf6692a39f5d757"
other = "{{.Key}}格式必须为 ipv6"

["StringValue.In"]
hash = "sha1-f62c039b8c1d6341acd56debdcf19c7724b5c9f9"
other = "{{.Key}}必须包含在{{.Arg0}}之内"

["StringValue.Lowercase"]
hash = "sha1-0e5fe3d4bddc12f69944859e4ee5eac9e9798879"
other = "{{.Key}}必须由小写字母组成"

["StringValue.Lt"]
hash = "sha1-1334da4edade0b11ae9430bf03bd654c9259928c"
other = "{{.Key}}长度必须小于{{.Arg0}}"

["StringValue.Lte"]
hash = "sha1-2d261c7732045db3b524c9f6faabb81dad0c2820"
other = "{{.Key}}长度必须小于等于{{.Arg0}}"

["StringValue.MatchRegexp"]
hash = "sha1-9fe6f8a87a765de0cd8722a84e99df54d319ca0e"
other = "{{.Key}}必须和给定的正则表达式相匹配"

["StringValue.MatchString"]
hash = "sha1-9fe6f8a87a765de0cd8722a84e99df54d319ca0e"
other = "{{.Key}}必须和给定的正则表达式相匹配"

["StringValue.Numeric"]
hash = "sha1-5680626260f416504d7991a847a17d2285e40c28"
other = "{{.Key}}必须由数字组成"

["StringValue.ParseRegexp"]
hash = "sha1-4ef2cd92007dc4a2e51e3c9127917a53e74de730"
other = "正则表达式解析失败"

["StringValue.Required"]
hash = "sha1-62b3289db46dac62320dc8987c9e8d943f4ea05f"
other = "{{.Key}}不能为空"

["StringValue.URL"]
hash = "sha1-0698125820390525bed477c9acd66b7295af5350"
other = "{{.Key}}格式必须为 url"

["StringValue.Uppercase"]
hash = "sha1-5917c5ecbbb34605c09d7df0596b5de4d1b45b57"
other = "{{.Key}}必须由大写字母组成"
